CREATE TABLE users(
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL UNIQUE,
	image VARCHAR(255) NULL,
	password VARCHAR(255) NOT NULL,
	is_available BOOLEAN NULL,
	session_token VARCHAR(255) NULL,
	create_at TIMESTAMP(0) NOT NULL,
	update_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE chats(
	id BIGSERIAL PRIMARY KEY,
	id_user1 BIGINT NOT NULL,
	id_user2 BIGINT NOT NULL,
	timestamp BIGINT NOT NULL,
	created_at TIMESTAMP(0) NOT NULL,
	updated_at TIMESTAMP(0) NOT NULL,
	FOREIGN KEY(id_user1) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_user2) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE messages(
	id BIGSERIAL PRIMARY KEY,
	message TEXT NOT NULL,
	url VARCHAR(255) NULL,
	is_image BOOLEAN DEFAULT FALSE,
	is_video BOOLEAN DEFAULT FALSE,
	id_sender BIGINT NOT NULL,
	id_receiver BIGINT NOT NULL,
	id_chat BIGINT NOT NULL,
	status VARCHAR(80) NOT NULL,
	timestamp BIGINT NOT NULL,
	created_at TIMESTAMP(0) NOT NULL,
	updated_at TIMESTAMP(0) NOT NULL,

	FOREIGN KEY(id_sender) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_receiver) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_chat) REFERENCES chats(id) ON DELETE CASCADE ON UPDATE CASCADE,

)